/**
 * Prioritized government portal backlog for live-adapter targeting.
 * Generated from the research catalog — extend adapters one portal at a time.
 */

export type PortalBacklogCategory =
  | "court_cases"
  | "criminal_history"
  | "sex_offender"
  | "warrants"
  | "inmate"
  | "sanctions"
  | "corporate"
  | "property"
  | "vital"
  | "professional_license"
  | "other";

export type PortalBacklogEntry = {
  jurisdiction: string;
  category: PortalBacklogCategory;
  name: string;
  url: string;
  searchType: string;
  approach: string;
  difficulty: "easy" | "medium" | "hard" | "blocked";
  notes: string;
  priority: "P0" | "P1" | "P2" | "P3";
  liveStatus: "live" | "candidate" | "portal_only" | "blocked";
};

export const PORTAL_BACKLOG: PortalBacklogEntry[] = [
  {
    jurisdiction: "Maryland",
    category: "court_cases",
    name: "Maryland Judiciary Case Search",
    url: "https://casesearch.mdcourts.gov/casesearch/",
    searchType: "party name, case #, court, filing date",
    approach: "form_post",
    difficulty: "blocked",
    notes:
      "Official terms expressly prohibit robots and automated scripts; pursue written data permission.",
    priority: "P0",
    liveStatus: "blocked",
  },
  {
    jurisdiction: "Florida — Miami-Dade County",
    category: "court_cases",
    name: "Miami-Dade Clerk Online Case Search / COIN",
    url: "https://www2.miami-dadeclerk.com/ocs/Search.aspx",
    searchType: "party/defendant name, case #, citation",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Separate civil-family-probate and criminal systems; advanced official-record searches can be fee-based.",
    priority: "P0",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Florida — Broward County",
    category: "court_cases",
    name: "Broward Clerk Case Search",
    url: "https://www.browardclerk.org/Records/Case-Search",
    searchType: "party name, case #, court division",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "County-only; confirm current public-document and rate-limit policy before implementation.",
    priority: "P0",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Florida — Hillsborough County",
    category: "court_cases",
    name: "Hillsborough HOVER Case Search",
    url: "https://hover.hillsclerk.com/html/case/caseSearch.html",
    searchType: "party name, case #, citation",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "HOVER portal; session behavior and public case-type coverage should be probed with permission.",
    priority: "P0",
    liveStatus: "live",
  },
  {
    jurisdiction: "Florida — Palm Beach County",
    category: "court_cases",
    name: "Palm Beach Clerk eCaseView",
    url: "https://appsgp.mypalmbeachclerk.com/eCaseView/",
    searchType: "party name, case #, citation",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Public portal is county-only; document access varies under Florida access matrix.",
    priority: "P0",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Florida — Orange County",
    category: "court_cases",
    name: "Orange County Clerk my eClerk",
    url: "https://myeclerk.myorangeclerk.com/home/index",
    searchType: "first/last name, business, case #, citation, date",
    approach: "captcha_heavy",
    difficulty: "hard",
    notes:
      "Anonymous users must complete CAPTCHA for every search; registered access expands protected records only.",
    priority: "P0",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Texas — statewide",
    category: "court_cases",
    name: "re:SearchTX",
    url: "https://research.txcourts.gov/",
    searchType: "party, attorney, judge, case #, case description",
    approach: "login_wall",
    difficulty: "hard",
    notes:
      "Free registered account required; 254 counties, mostly e-filed records; public users do not get criminal/JP coverage.",
    priority: "P0",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Texas — Bexar County",
    category: "court_cases",
    name: "Bexar County Justice Portal",
    url: "https://portal-txbexar.tylertech.cloud/Portal/",
    searchType: "name, record #, business, court, case type/date",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Tyler Odyssey Smart Search; cookie/session dependent, likely reusable with other Odyssey adapters.",
    priority: "P0",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Texas — Harris County",
    category: "court_cases",
    name: "Harris County District Clerk eDocs",
    url: "https://www.hcdistrictclerk.com/eDocs/Public/Search.aspx?ShowFF=1",
    searchType: "party name/type, case #, DOB for criminal refinement",
    approach: "login_wall",
    difficulty: "hard",
    notes:
      "Free registered login now required; clerk warns it may suspend/reduce congesting accounts.",
    priority: "P0",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "New York — statewide Supreme Civil",
    category: "court_cases",
    name: "WebCivil Supreme",
    url: "https://iapps.courts.state.ny.us/webcivil/FCASMain",
    searchType: "party, index #, attorney/firm, justice, county",
    approach: "captcha_heavy",
    difficulty: "blocked",
    notes:
      "Party search is broad, but current submit flow uses hCaptcha; do not attempt CAPTCHA bypass.",
    priority: "P0",
    liveStatus: "blocked",
  },
  {
    jurisdiction: "New York — local civil/housing",
    category: "court_cases",
    name: "WebCivil Local",
    url: "https://iapps.courts.state.ny.us/webcivilLocal/LCMain",
    searchType: "party, index #, attorney/firm, local court",
    approach: "captcha_heavy",
    difficulty: "blocked",
    notes:
      "Shares NY court anti-automation / hCaptcha behavior; useful only through approved access or user-mediated search.",
    priority: "P0",
    liveStatus: "blocked",
  },
  {
    jurisdiction: "New York — statewide",
    category: "court_cases",
    name: "eCourts",
    url: "https://iapps.courts.state.ny.us/webcivil/ecourtsMain",
    searchType: "case #, party, court/county",
    approach: "captcha_heavy",
    difficulty: "hard",
    notes:
      "Coverage varies by court; validate each target surface separately and respect public-access controls.",
    priority: "P0",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "California — Los Angeles County",
    category: "court_cases",
    name: "LA Superior Court Public Access Online Services",
    url: "https://www.lacourt.org/paos/v2public/CivilIndex",
    searchType: "party/defendant name, company, case #",
    approach: "login_wall",
    difficulty: "hard",
    notes:
      "Name searches require guest/registered workflow and payment before results; high-volume pricing exists.",
    priority: "P0",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "California — Orange County",
    category: "court_cases",
    name: "Orange County Superior Court Case Name Search",
    url: "https://namesearch.occourts.org/",
    searchType: "last name, filing-date range, driver's license",
    approach: "login_wall",
    difficulty: "hard",
    notes:
      "Free enrollment/login is mandatory for name search; public case-number search is separate.",
    priority: "P0",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "California — San Diego County",
    category: "court_cases",
    name: "San Diego Superior Court Index",
    url: "https://courtindex.sdcourt.ca.gov/CISPublic/",
    searchType: "party name, case #, DA case #",
    approach: "captcha_heavy",
    difficulty: "hard",
    notes:
      "Cloudflare challenge is visible; index omits charges/dispositions and is not the official record.",
    priority: "P0",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "California — Santa Clara County",
    category: "court_cases",
    name: "Santa Clara Superior Court Public Portal",
    url: "https://portal.scscourt.org/search",
    searchType: "party name, business, case #, court/case type",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Modern court portal; validate account, document, and per-search controls before scaling.",
    priority: "P0",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "California — Alameda County",
    category: "court_cases",
    name: "Alameda eCourt Public Portal",
    url: "https://eportal.alameda.courts.ca.gov/?q=Home",
    searchType: "party and case information",
    approach: "login_wall",
    difficulty: "hard",
    notes:
      "Account required; civil, family, probate, mental-health and adoption coverage, not all case types.",
    priority: "P0",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "California — Riverside County",
    category: "court_cases",
    name: "Riverside Superior Court Public Access",
    url: "https://epublic-access.riverside.courts.ca.gov/public-portal/",
    searchType: "party name, case #, case type",
    approach: "login_wall",
    difficulty: "blocked",
    notes:
      "Account required; explicit 30 searches per 5 minutes and stated prohibition on scripts/circumvention.",
    priority: "P0",
    liveStatus: "blocked",
  },
  {
    jurisdiction: "California — Sacramento County",
    category: "court_cases",
    name: "Sacramento Superior Court Public Case Access",
    url: "https://services.saccourt.ca.gov/PublicCaseAccess/",
    searchType: "name, case #, filing date",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "No online search/download fee; case-type detail varies, subscriptions add notifications.",
    priority: "P0",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Illinois — Cook County",
    category: "court_cases",
    name: "Cook County Clerk Online Case Information / CCCPortal",
    url: "https://www.cookcountyclerkofcourt.org/online-case-information",
    searchType: "party/case; case-type-specific portals",
    approach: "ajax_json",
    difficulty: "hard",
    notes:
      "Civil and criminal/domestic access split; validate which public search endpoints remain available.",
    priority: "P0",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Arizona — statewide",
    category: "court_cases",
    name: "Arizona Judicial Branch Public Access Case Lookup",
    url: "https://apps.azcourts.gov/publicaccess/",
    searchType: "party name, case #, court, filing date",
    approach: "captcha_heavy",
    difficulty: "hard",
    notes:
      "177 of 184 courts, but random verification words throttle high-volume use; state invites high-volume-access inquiries.",
    priority: "P0",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Arizona — Maricopa County",
    category: "court_cases",
    name: "Maricopa County Superior Court Docket",
    url: "https://www.superiorcourt.maricopa.gov/Docket/",
    searchType: "party/case, civil/criminal/family/probate",
    approach: "form_post",
    difficulty: "medium",
    notes:
      "Large metro docket source; date/case-type paths may be separate and daily auditing can alter entries.",
    priority: "P0",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Pennsylvania — statewide",
    category: "court_cases",
    name: "Pennsylvania UJS Portal Case Search",
    url: "https://ujsportal.pacourts.us/CaseSearch",
    searchType: "participant, organization, case/docket #, state ID",
    approach: "form_post",
    difficulty: "medium",
    notes:
      "Live via CaseSearch form POST. ParticipantName requires County (e.g. Philadelphia). Antiforgery token from landing page.",
    priority: "P0",
    liveStatus: "live",
  },
  {
    jurisdiction: "Indiana — statewide",
    category: "court_cases",
    name: "Indiana Courts MyCase",
    url: "https://public.courts.in.gov/MyCase",
    searchType: "party, attorney, business, case/citation/cross-reference #",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Live via /mycase/Search/SearchCases with Mode=ByParty, First/Last. Captcha optional; CourtItemID 92 = All Odyssey Courts.",
    priority: "P0",
    liveStatus: "live",
  },
  {
    jurisdiction: "Wisconsin — statewide",
    category: "court_cases",
    name: "Wisconsin Circuit Court Access (CCAP)",
    url: "https://wcca.wicourts.gov/case.html",
    searchType: "party name, case #, county, date",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Live via /jsonPost/caseSearch (SPA twin). Gated /api/* returns 403.",
    priority: "P0",
    liveStatus: "live",
  },
  {
    jurisdiction: "Michigan — statewide",
    category: "court_cases",
    name: "MiCOURT Case Search",
    url: "https://micourt.courts.michigan.gov/case-search/court/",
    searchType: "party name, case #, court, date",
    approach: "ajax_json",
    difficulty: "hard",
    notes:
      "Coverage and fields vary by participating court; modern client application needs endpoint/terms review.",
    priority: "P0",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Missouri — statewide",
    category: "court_cases",
    name: "Missouri Case.net",
    url: "https://www.courts.mo.gov/casenet/base/welcome.do",
    searchType: "litigant, attorney, case #, county",
    approach: "form_post",
    difficulty: "medium",
    notes:
      "Extensive circuit/appellate coverage; record availability and bot controls can change without notice.",
    priority: "P0",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Minnesota — statewide",
    category: "court_cases",
    name: "Minnesota Court Records Online (MCRO)",
    url: "https://publicaccess.courts.state.mn.us/CaseSearch",
    searchType: "person/business/attorney, case/citation, hearings",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Public district court records/documents; no charge, but document visibility follows court access rules.",
    priority: "P0",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Arkansas — statewide",
    category: "court_cases",
    name: "ARCourts CourtConnect",
    url: "https://caseinfo.arcourts.gov/cconnect/PROD/public/ck_public_qry_main.cp_main_idx",
    searchType: "party name, case #, court, date",
    approach: "form_post",
    difficulty: "medium",
    notes:
      "Odyssey-style public portal; county/court participation and document access vary.",
    priority: "P0",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "New Jersey — statewide",
    category: "court_cases",
    name: "New Jersey Courts Find a Case",
    url: "https://www.njcourts.gov/public/find-a-case",
    searchType:
      "party/defendant, case #, county; separate civil/criminal portals",
    approach: "captcha_heavy",
    difficulty: "hard",
    notes:
      "Municipal search has CAPTCHA; civil, criminal, judgment and tax surfaces are separate.",
    priority: "P0",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Connecticut — statewide",
    category: "court_cases",
    name: "Connecticut Judicial Criminal/Motor Vehicle Docket Search",
    url: "https://www.jud2.ct.gov/crdockets/SearchByDefendant.aspx",
    searchType: "defendant name, case #, court",
    approach: "form_post",
    difficulty: "medium",
    notes:
      "Use separate state judicial surfaces for civil/family; do not treat this as a full criminal-history check.",
    priority: "P0",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "North Carolina — statewide rollout",
    category: "court_cases",
    name: "North Carolina eCourts Portal",
    url: "https://portal-nc.tylertech.cloud/Portal/",
    searchType: "name, case #, county, hearing/judgment",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Tyler portal supports Smart Search and Judgment Search; coverage depends on eCourts rollout.",
    priority: "P0",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Washington — statewide",
    category: "court_cases",
    name: "Washington Courts Odyssey Portal",
    url: "https://odysseyportal.courts.wa.gov/ODYPortal",
    searchType: "name, record #, court, case type/status/date",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Tyler Smart Search pattern; test court participation and document visibility rather than assuming full coverage.",
    priority: "P0",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Idaho — statewide",
    category: "court_cases",
    name: "Idaho iCourt Portal",
    url: "https://portal-idaho.tylertech.cloud/odysseyportal/Home/Dashboard/29",
    searchType: "name, record #, business, court, case type/date",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Public Smart Search supports wildcards; likely a reusable Tyler adapter with session handling.",
    priority: "P0",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Utah — statewide",
    category: "court_cases",
    name: "Utah XChange Public Court Records",
    url: "https://legacy.utcourts.gov/records/coris/",
    searchType: "party name, case #, court",
    approach: "login_wall",
    difficulty: "hard",
    notes:
      "Broad district/justice access is paid subscription or courthouse/library terminal; MyCase is not a public statewide search.",
    priority: "P0",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Iowa — statewide",
    category: "court_cases",
    name: "Iowa Courts Online Search",
    url: "https://www.iowacourts.state.ia.us/ESAWebApp/TrialSimpFrame",
    searchType: "party name, case #, citation, county",
    approach: "form_post",
    difficulty: "medium",
    notes:
      "Legacy web application; validate CAPTCHA and court-record exclusions in a permitted proof of concept.",
    priority: "P0",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "New Mexico — statewide",
    category: "court_cases",
    name: "New Mexico Courts Case Lookup",
    url: "https://caselookup.nmcourts.gov/caselookup/app",
    searchType: "party name, case #, court, date",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Public case lookup; scope and documents vary by court and case type.",
    priority: "P0",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "North Dakota — statewide",
    category: "court_cases",
    name: "North Dakota Courts Public Search",
    url: "https://publicsearch.ndcourts.gov/default.aspx",
    searchType: "party name, case #, court",
    approach: "form_post",
    difficulty: "medium",
    notes:
      "Public statewide docket surface; verify search limits and current access rules.",
    priority: "P0",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Delaware — statewide civil",
    category: "court_cases",
    name: "Delaware CourtConnect",
    url: "https://courtconnect.courts.delaware.gov/",
    searchType: "person/company name, case type, filing date",
    approach: "form_post",
    difficulty: "easy",
    notes:
      "Civil case information with partial and phonetic name search; Family Court is excluded.",
    priority: "P0",
    liveStatus: "live",
  },
  {
    jurisdiction: "Oklahoma — statewide",
    category: "court_cases",
    name: "Oklahoma State Courts Network (OSCN)",
    url: "https://www.oscn.net/dockets/search.aspx",
    searchType: "party name, case #, county, attorney",
    approach: "form_post",
    difficulty: "easy",
    notes:
      "Legacy public docket search; coverage is strongest for participating district/appellate courts.",
    priority: "P0",
    liveStatus: "live",
  },
  {
    jurisdiction: "United States — federal",
    category: "inmate",
    name: "Federal Bureau of Prisons Inmate Locator",
    url: "https://www.bop.gov/inmateloc/",
    searchType: "name, BOP/DCDC/FBI/INS #, age/race/sex",
    approach: "form_post",
    difficulty: "easy",
    notes:
      "Federal custody from 1982-present; release dates may change as sentences are recalculated.",
    priority: "P1",
    liveStatus: "live",
  },
  {
    jurisdiction: "California",
    category: "inmate",
    name: "CDCR California Incarcerated Records and Information Search",
    url: "https://apps.cdcr.ca.gov/ciris",
    searchType: "name, CDCR #, age, location",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Public selected records only; CDCR warns against mistaken identity and misuse.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Texas",
    category: "inmate",
    name: "Texas Department of Criminal Justice Inmate Search",
    url: "https://inmate.tdcj.texas.gov/InmateSearch/start.action",
    searchType: "last + first initial, TDCJ #, SID, race/sex",
    approach: "form_post",
    difficulty: "easy",
    notes:
      "Exact last-name behavior; current TDCJ custody only and data is at least one working day old.",
    priority: "P1",
    liveStatus: "candidate",
  },
  {
    jurisdiction: "Florida",
    category: "inmate",
    name: "Florida Department of Corrections Offender Search",
    url: "https://pubapps.fdc.myflorida.com/OffenderSearch/Search.aspx",
    searchType: "name, DC #, photo/other filters",
    approach: "form_post",
    difficulty: "medium",
    notes:
      "State DOC custody data; confirm current CAPTCHA and terms before a live adapter.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "New York",
    category: "inmate",
    name: "NYS DOCCS Incarcerated Lookup",
    url: "https://nysdoccslookup.doccs.ny.gov/",
    searchType: "name, DIN, NYSID, DOB",
    approach: "form_post",
    difficulty: "medium",
    notes:
      "Live extract from DOCCS main database; supports some former incarcerated people and excludes youthful offenders.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Pennsylvania",
    category: "inmate",
    name: "Pennsylvania DOC Inmate and Parolee Locator",
    url: "https://inmatelocator.cor.pa.gov/",
    searchType: "last name, inmate #; first name optional",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "State-sentenced inmates/parolees; excludes county and out-of-state custody.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Illinois",
    category: "inmate",
    name: "Illinois DOC Individual in Custody Search",
    url: "https://idoc.illinois.gov/offender/inmatesearch.html",
    searchType: "name, IDOC #, birth date",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "State custody only; check policy before collecting photos or historical details.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Ohio",
    category: "inmate",
    name: "Ohio DRC Offender Search",
    url: "https://appgateway.drc.ohio.gov/OffenderSearch",
    searchType: "name, offender #, county, DOB, location",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Includes incarceration, supervision and judicial release; supports partial surname matching.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Michigan",
    category: "inmate",
    name: "Michigan OTIS Offender Tracking Information System",
    url: "https://mdocweb.state.mi.us/otis2/otis2.aspx",
    searchType: "name, MDOC #, DOB, status",
    approach: "form_post",
    difficulty: "medium",
    notes:
      "State corrections records; verify the current search form and availability before deployment.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Georgia",
    category: "inmate",
    name: "Georgia DOC Offender Query",
    url: "https://services.gdc.ga.gov/GDC/OffenderQuery/jsp/OffQryForm.jsp",
    searchType: "name, GDC ID, aliases, facility/status",
    approach: "form_post",
    difficulty: "easy",
    notes:
      "Public current-custody search with photo where available; state disclaimer applies.",
    priority: "P1",
    liveStatus: "candidate",
  },
  {
    jurisdiction: "North Carolina",
    category: "inmate",
    name: "NC DPS Offender Public Information Search",
    url: "https://webapps.doc.state.nc.us/opi/offendersearch.do?method=view",
    searchType: "name, offender #, demographics",
    approach: "form_post",
    difficulty: "medium",
    notes:
      "State prison/offender data; distinguish from county-jail and court records.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Virginia",
    category: "inmate",
    name: "Virginia DOC Inmate and Supervisee Locator",
    url: "https://vadoc.virginia.gov/general-public/inmate-and-supervisee-locator/",
    searchType: "first/last name or DOC ID; location/race/age/sex",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Includes custody and community supervision; updated daily and the agency warns data can lag.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Arizona",
    category: "inmate",
    name: "Arizona DOC Inmate Data Search",
    url: "https://corrections.az.gov/public-resources/inmate-datasearch",
    searchType: "name, ADC #, status/facility",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "State-level custody data; do not conflate prison status with local jail data.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Washington",
    category: "inmate",
    name: "Washington DOC Incarcerated Search",
    url: "https://doc.wa.gov/records/incarcerated-data-search/incarcerated-search",
    searchType: "name or DOC #",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Current DOC incarceration only; public terms require users to verify status independently.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Oregon",
    category: "inmate",
    name: "Oregon VISOR",
    url: "https://visor.oregon.gov/",
    searchType: "full/partial name, SID, county ID",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Current custody or supervision; registration is only needed for notifications, not basic search.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Colorado",
    category: "inmate",
    name: "Colorado DOC Offender Search",
    url: "https://www.doc.state.co.us/oss/",
    searchType: "name, DOC #, location/status",
    approach: "form_post",
    difficulty: "medium",
    notes:
      "State custody data; inspect terms/rate behavior before a production adapter.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Indiana",
    category: "inmate",
    name: "Indiana DOC Offender Database Search",
    url: "https://www.in.gov/idoc/offender-information/offender-database-search/",
    searchType: "name, DOC #, age/sex/race",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "State offender records; pair with Indiana MyCase only as corroboration, not identity proof.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Wisconsin",
    category: "inmate",
    name: "Wisconsin DOC Offender Locator",
    url: "https://appsdoc.wi.gov/lop/",
    searchType: "name, DOC #, demographics",
    approach: "form_post",
    difficulty: "medium",
    notes:
      "State custody/supervision availability varies; check current consent and data-use language.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Minnesota",
    category: "inmate",
    name: "Minnesota DOC Offender Locator",
    url: "https://coms.doc.state.mn.us/PublicViewer/",
    searchType: "name, MNDOC #, age/sex",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Public corrections information; results and historical coverage should be validated per person.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Tennessee",
    category: "inmate",
    name: "Tennessee Felony Offender Information Lookup",
    url: "https://foil.app.tn.gov/foil/search.jsp",
    searchType: "name, TDOC ID, state ID, race/aliases",
    approach: "captcha_heavy",
    difficulty: "hard",
    notes:
      "Visual/audio CAPTCHA is mandatory for name search; no compliant unattended adapter without permission.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Missouri",
    category: "inmate",
    name: "Missouri DOC Offender Search",
    url: "https://web.mo.gov/doc/offSearchWeb/",
    searchType: "name, DOC #, age/sex",
    approach: "form_post",
    difficulty: "medium",
    notes:
      "State corrections search; validate output limits and current accessibility controls.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "New Jersey",
    category: "inmate",
    name: "New Jersey DOC Offender Search",
    url: "https://www20.state.nj.us/DOC_Inmate/inmatefinder?i=I",
    searchType: "name, SBI #, inmate #",
    approach: "form_post",
    difficulty: "medium",
    notes:
      "State DOC locator; separate from NJ court systems and county jails.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Connecticut",
    category: "inmate",
    name: "Connecticut DOC Inmate Search",
    url: "https://portal.ct.gov/DOC/Services/Inmate-Search",
    searchType: "name, DOB, CT DOC #",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Nightly OBIS feed; current DOC custody only and statutory exclusions apply.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Maryland",
    category: "inmate",
    name: "Maryland DPSCS Inmate Locator",
    url: "https://dpscs.maryland.gov/services/inmate-locator.shtml",
    searchType: "name, SID, inmate #",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "State facility data only; do not infer complete criminal history or local-jail status.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Kentucky",
    category: "inmate",
    name: "Kentucky Offender Online Lookup (KOOL)",
    url: "https://kool.corrections.ky.gov/KOOL/",
    searchType: "name, offender PID, facility, supervision status",
    approach: "form_post",
    difficulty: "easy",
    notes:
      "Covers incarceration and community supervision; agency recommends minimal criteria for matching.",
    priority: "P1",
    liveStatus: "candidate",
  },
  {
    jurisdiction: "United States — National",
    category: "sex_offender",
    name: "NSOPW Dru Sjodin National Sex Offender Public Website",
    url: "https://www.nsopw.gov/?AspxAutoDetectCookieSupport=1",
    searchType: "first+last name and/or ZIP; optional state, city, county",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Live via nsopw-api.ojp.gov with got-scraping (Cloudflare). Parallel with VA/FL state twins when query cues match.",
    priority: "P1",
    liveStatus: "live",
  },
  {
    jurisdiction: "Canada — National",
    category: "sex_offender",
    name: "RCMP High Risk Child Sex Offender Database",
    url: "https://rcmp.ca/en/high-risk-child-sex-offender-database",
    searchType: "name; optional city/province filter client-side",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Live Drupal scrape of public high-risk profiles only. Full Canadian NSOR remains law-enforcement only. Runs in parallel with NSOPW on National SOR.",
    priority: "P1",
    liveStatus: "live",
  },
  {
    jurisdiction: "New York",
    category: "corporate",
    name: "NY DOS Active Corporations Open Data",
    url: "https://data.ny.gov/Economic-Development/Active-Corporations-Beginning-1800/n9v6-gdp6",
    searchType: "entity name; optional county/city/ZIP",
    approach: "public_api",
    difficulty: "easy",
    notes: "Live Socrata twin. Parallel with FL Sunbiz when NY cues present.",
    priority: "P1",
    liveStatus: "live",
  },
  {
    jurisdiction: "United States — federal",
    category: "corporate",
    name: "IRS Exempt Organizations (ProPublica / EO BMF)",
    url: "https://projects.propublica.org/nonprofits/",
    searchType: "organization name; optional state/city",
    approach: "public_api",
    difficulty: "easy",
    notes: "Live ProPublica Nonprofit Explorer API mirroring IRS EO BMF.",
    priority: "P1",
    liveStatus: "live",
  },
  {
    jurisdiction: "Illinois — Kane County",
    category: "property",
    name: "Kane County Assessor Parcel Owner (ArcGIS)",
    url: "https://gistech.countyofkane.org/arcgis/rest/services/KanePINList/MapServer/0",
    searchType: "owner/tax name",
    approach: "public_api",
    difficulty: "easy",
    notes:
      "Live ArcGIS TaxName query. Cook County open GIS omits owner names (portal-only).",
    priority: "P1",
    liveStatus: "live",
  },
  {
    jurisdiction: "California",
    category: "sex_offender",
    name: "California Megan's Law Website",
    url: "https://www.meganslaw.ca.gov/",
    searchType: "name, location, ZIP, map",
    approach: "captcha_heavy",
    difficulty: "hard",
    notes:
      "Daily updates, but legal-disclosure limits and strong misuse warnings; use only within permitted public-safety scope.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Florida",
    category: "sex_offender",
    name: "FDLE Sexual Offender and Predator Search",
    url: "https://offender.fdle.state.fl.us/offender/sops/home.jsf",
    searchType: "name, location, county, address, status",
    approach: "form_post",
    difficulty: "medium",
    notes:
      "Live via home.jsf jakarta.faces ViewState + name POST (PrimeFaces). Results page is offenderSearch.jsf datagrid.",
    priority: "P1",
    liveStatus: "live",
  },
  {
    jurisdiction: "Texas",
    category: "sex_offender",
    name: "Texas DPS Sex Offender Registry",
    url: "https://publicsite.dps.texas.gov/SexOffenderRegistry/Search",
    searchType: "name, address, ZIP, county, offender #",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "State-specific registry can supplement partial NSOPW coverage; validate current API/anti-bot behavior.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "New York",
    category: "sex_offender",
    name: "New York DCJS Sex Offender Registry",
    url: "https://www.criminaljustice.ny.gov/SomsSUBDirectory/search_index.jsp",
    searchType: "name, county, ZIP",
    approach: "form_post",
    difficulty: "medium",
    notes:
      "Online directory is limited to Level 2 and 3; Level 1 requires other access channels.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Pennsylvania",
    category: "sex_offender",
    name: "Pennsylvania Megan's Law Public Website",
    url: "https://www.pameganslaw.state.pa.us/",
    searchType: "name, location, county, ZIP",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "State registry; follow statutory purpose restrictions and document result timestamps.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "California",
    category: "professional_license",
    name: "California Department of Consumer Affairs License Search",
    url: "https://search.dca.ca.gov/",
    searchType: "licensee name, license #, board/type",
    approach: "captcha_heavy",
    difficulty: "hard",
    notes:
      "General DCA search is WAF-protected; board-specific feeds may be more viable than this aggregate UI.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Florida",
    category: "professional_license",
    name: "Florida DBPR License Search",
    url: "https://www.myfloridalicense.com/wl11.asp?brd=&mode=1&t=",
    searchType: "licensee/business name, license #, county/type",
    approach: "form_post",
    difficulty: "medium",
    notes:
      "Broad occupations; search result fields and board coverage are configurable through the form.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "New York",
    category: "professional_license",
    name: "New York Office of the Professions Verification Search",
    url: "https://www.op.nysed.gov/verification-search",
    searchType: "professional name, license #, profession",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Primary professional-license data; board-specific disciplinary records can be separate.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Texas",
    category: "professional_license",
    name: "Texas Department of Licensing and Regulation Verify a License",
    url: "https://license.state.tx.us/verify.htm",
    searchType: "individual/business name, license #, industry",
    approach: "form_post",
    difficulty: "easy",
    notes:
      "Includes searchable enforcement actions; not a substitute for separate Texas medical/nursing boards.",
    priority: "P1",
    liveStatus: "candidate",
  },
  {
    jurisdiction: "Pennsylvania",
    category: "professional_license",
    name: "Pennsylvania Licensing System (PALS)",
    url: "https://www.pals.pa.gov/#/page/default",
    searchType: "name, license #, profession",
    approach: "ajax_json",
    difficulty: "medium",
    notes: "Modern SPA; inspect network and written terms before integration.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Virginia",
    category: "professional_license",
    name: "Virginia DHP License Lookup",
    url: "https://dhp.virginiainteractive.org/Lookup/Index",
    searchType: "name, license #, profession",
    approach: "login_wall",
    difficulty: "medium",
    notes:
      "Free service is explicitly for occasional/low-volume use; official subscription/bulk options exist.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Georgia",
    category: "professional_license",
    name: "Georgia Professional Licensing Verification",
    url: "https://verify.sos.ga.gov/Verification/",
    searchType: "name, license #, profession",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Secretary of State licensing portal; confirm board-specific data and search rate policy.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Washington",
    category: "professional_license",
    name: "Washington DOH Provider Credential Search",
    url: "https://doh.wa.gov/licenses-permits-and-certificates/provider-credential-or-facility-search",
    searchType: "individual/business name, credential #",
    approach: "public_api",
    difficulty: "easy",
    notes:
      "DOH explicitly asks high-volume users to use its Open Data Portal rather than scrape the UI.",
    priority: "P1",
    liveStatus: "candidate",
  },
  {
    jurisdiction: "Illinois",
    category: "professional_license",
    name: "Illinois IDFPR License Lookup",
    url: "https://online-dfpr.micropact.com/lookup/licenselookup.aspx",
    searchType: "name, license #, profession",
    approach: "form_post",
    difficulty: "medium",
    notes:
      "Public lookup through vendor-hosted portal; validate CAPTCHA/rate limits and disciplinary fields.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "New Jersey",
    category: "professional_license",
    name: "New Jersey License Verification",
    url: "https://newjersey.mylicense.com/verification/",
    searchType: "name, license #, board/license type",
    approach: "ajax_json",
    difficulty: "medium",
    notes: "Vendor portal; account-only actions must remain out of scope.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Ohio",
    category: "professional_license",
    name: "Ohio eLicense Look-Up",
    url: "https://elicense.ohio.gov/oh_verifylicense",
    searchType: "last name + first initial, license #, board",
    approach: "ajax_json",
    difficulty: "medium",
    notes: "24 state agencies/boards; data is reported as daily updated.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Michigan",
    category: "professional_license",
    name: "Michigan LARA License Verification",
    url: "https://www.lara.michigan.gov/colaLicVerify/",
    searchType: "name, license #, profession",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "State licensing lookup; verify data coverage across LARA-administered professions.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Massachusetts",
    category: "professional_license",
    name: "Massachusetts Check a License",
    url: "https://elicensing.mass.gov/CitizenAccess/GeneralProperty/PropertyLookUp.aspx?isLicensee=Y",
    searchType: "name, license #, license type",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Citizen Access platform; shared account flow should not be automated without authorization.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Connecticut",
    category: "professional_license",
    name: "Connecticut eLicense License Lookup",
    url: "https://www.elicense.ct.gov/lookup/licenselookup.aspx",
    searchType: "name, license #, category/status",
    approach: "form_post",
    difficulty: "easy",
    notes:
      "State describes results as instant, primary-source verification; broad occupation coverage.",
    priority: "P1",
    liveStatus: "candidate",
  },
  {
    jurisdiction: "Colorado",
    category: "professional_license",
    name: "Colorado DORA License Lookup",
    url: "https://apps2.colorado.gov/dora/licensing/Lookup/LicenseLookup.aspx",
    searchType: "first/last name, license #, profession",
    approach: "public_api",
    difficulty: "easy",
    notes:
      "Site expressly says not to crawl; Colorado Information Marketplace offers nightly data/API options.",
    priority: "P1",
    liveStatus: "candidate",
  },
  {
    jurisdiction: "California",
    category: "professional_license",
    name: "State Bar of California Attorney Search",
    url: "https://apps.calbar.ca.gov/",
    searchType: "attorney name, bar #, advanced profile fields",
    approach: "form_post",
    difficulty: "medium",
    notes:
      "Official legal regulator profile includes public discipline history; use narrow, audited search patterns.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "New York",
    category: "professional_license",
    name: "New York Unified Court System Attorney Search",
    url: "https://iapps.courts.state.ny.us/attorney/AttorneySearch",
    searchType: "attorney name, registration #, city/status/year admitted",
    approach: "form_post",
    difficulty: "medium",
    notes:
      "Attorney-registration database, not a general professional registry; New York does not use traditional bar numbers.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Texas",
    category: "professional_license",
    name: "State Bar of Texas Find A Lawyer",
    url: "https://www.texasbar.com/findalawyer/",
    searchType: "attorney name, bar #, city/practice filters",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Official membership directory; access is public-use only and profile data should be attributed to the bar.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Florida",
    category: "professional_license",
    name: "The Florida Bar Member Directory",
    url: "https://www.floridabar.org/directories/find-mbr/",
    searchType: "attorney name, bar #, city/status",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Court-regulated attorney directory; disciplinary history/profile views may have separate endpoints.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "International — United Nations",
    category: "sanctions",
    name: "UN Security Council Consolidated List",
    url: "https://scsanctions.un.org/resources/xml/en/consolidated.xml",
    searchType: "name, alias, DOB, nationality, list ID",
    approach: "public_api",
    difficulty: "easy",
    notes:
      "Official XML (also HTML/PDF); machine-readable bulk feed, not a REST API.",
    priority: "P1",
    liveStatus: "candidate",
  },
  {
    jurisdiction: "International — European Union",
    category: "sanctions",
    name: "EU Consolidated Financial Sanctions List",
    url: "https://data.europa.eu/data/datasets/consolidated-list-of-persons-groups-and-entities-subject-to-eu-financial-sanctions?locale=en",
    searchType: "name, alias, DOB, regulation/list ID",
    approach: "public_api",
    difficulty: "easy",
    notes:
      "Official dataset publishes GLOBAL/DELTA XML concepts; normalize separately from OFAC/OpenSanctions.",
    priority: "P1",
    liveStatus: "candidate",
  },
  {
    jurisdiction: "United Kingdom",
    category: "sanctions",
    name: "UK Sanctions List",
    url: "https://www.gov.uk/government/publications/the-uk-sanctions-list",
    searchType: "name, alias, DOB, regime, unique ID",
    approach: "public_api",
    difficulty: "easy",
    notes:
      "Official XML/CSV includes direct structured downloads; use version/update timestamps.",
    priority: "P1",
    liveStatus: "candidate",
  },
  {
    jurisdiction: "Canada",
    category: "sanctions",
    name: "Consolidated Canadian Autonomous Sanctions List",
    url: "https://www.international.gc.ca/world-monde/international_relations-relations_internationales/sanctions/consolidated-consolide.aspx?lang=eng",
    searchType: "name, alias, DOB, regulation, listing date",
    approach: "public_api",
    difficulty: "easy",
    notes:
      "Official XML/HTML/PDF; page warns regulations remain authoritative over the consolidated display.",
    priority: "P1",
    liveStatus: "candidate",
  },
  {
    jurisdiction: "Australia",
    category: "sanctions",
    name: "Australian Sanctions Consolidated List",
    url: "https://www.dfat.gov.au/international-relations/security/sanctions/consolidated-list",
    searchType: "name, alias, DOB, citizenship, address, regime",
    approach: "public_api",
    difficulty: "easy",
    notes:
      "Official XLSX download; includes targeted financial sanctions and travel bans.",
    priority: "P1",
    liveStatus: "candidate",
  },
  {
    jurisdiction: "Switzerland",
    category: "sanctions",
    name: "SECO Search for Subjects of Sanctions",
    url: "https://www.seco.admin.ch/en/searching-for-subjects-sanctions",
    searchType: "name, entity, sanction set",
    approach: "public_api",
    difficulty: "easy",
    notes:
      "Official search plus downloadable XML and Excel; XML specification is published for automated processing.",
    priority: "P1",
    liveStatus: "candidate",
  },
  {
    jurisdiction: "International — World Bank",
    category: "sanctions",
    name: "World Bank Listing of Ineligible Firms and Individuals",
    url: "https://documents.worldbank.org/en/projects-operations/procurement/debarred-firms",
    searchType: "individual/entity name, sanction type/date",
    approach: "ajax_json",
    difficulty: "easy",
    notes:
      "Official table updates every three hours; includes debarred and cross-debarred parties.",
    priority: "P1",
    liveStatus: "candidate",
  },
  {
    jurisdiction: "International — Asian Development Bank",
    category: "sanctions",
    name: "ADB Debarment and Suspension Register",
    url: "https://www.adb.org/who-we-are/integrity/sanctions",
    searchType: "individual/entity name, sanction status/date",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Official register and cross-debarment data; confirm current downloadable/register endpoint.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "International — Inter-American Development Bank",
    category: "sanctions",
    name: "IDB Sanctioned Firms and Individuals Dataset",
    url: "https://data.iadb.org/dataset/dataset-of-sanctioned-firms-and-individuals",
    searchType: "individual/entity name, sanction, date",
    approach: "public_api",
    difficulty: "easy",
    notes:
      "Official open-data dataset with download options; distinct from the general IDB web table.",
    priority: "P1",
    liveStatus: "candidate",
  },
  {
    jurisdiction: "European Union / ENFAST",
    category: "warrants",
    name: "Europe's Most Wanted Fugitives",
    url: "https://eumostwanted.eu/",
    searchType: "name, country, crime category",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Content is published by national ENFAST teams with Europol support; no official bulk API advertised.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Canada",
    category: "warrants",
    name: "RCMP Wanted by the RCMP",
    url: "https://www.rcmp-grc.gc.ca/en/wanted",
    searchType: "name, crime/offense, jurisdiction",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Official public cards/search filters; do not treat absence as proof that a person is not wanted.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Canada",
    category: "warrants",
    name: "Canada Border Services Agency Wanted List",
    url: "https://www.cbsa-asfc.gc.ca/wc-cg/menu-eng.html",
    searchType: "name, alleged violation, nationality/status",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Public wanted list is narrower than criminal warrants; source-specific identity matching is essential.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "New Zealand",
    category: "warrants",
    name: "New Zealand Police Wanted for Arrest",
    url: "https://www.police.govt.nz/can-you-help-us/wanted-arrest",
    searchType: "name, district, wanted category",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Public wanted-person listings; preserve the issuing district and retrieval timestamp.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Australia",
    category: "warrants",
    name: "Australian Federal Police Most Wanted",
    url: "https://www.afp.gov.au/what-we-do/crime-types/most-wanted",
    searchType: "name, offense/category",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Curated public fugitives rather than a complete warrant registry; pages can be CMS-driven.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "United States — federal",
    category: "other",
    name: "DOJ Foreign Agents Registration Act Search / API",
    url: "https://efile.fara.gov/ords/fara/f?p=1235:10",
    searchType:
      "registrant, short-form person, foreign principal, document/date",
    approach: "public_api",
    difficulty: "easy",
    notes:
      "Official searchable filings, daily bulk repository, and public API; strong high-value name/affiliation source.",
    priority: "P1",
    liveStatus: "candidate",
  },
  {
    jurisdiction: "United States — federal",
    category: "corporate",
    name: "SEC EDGAR Company and Full-Text Search",
    url: "https://www.sec.gov/edgar/search/",
    searchType: "company, officer/signatory text, CIK, filing/date",
    approach: "public_api",
    difficulty: "medium",
    notes:
      "Use SEC-required descriptive User-Agent and published rate guidance; company/filing data, not a people registry.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "United States — federal",
    category: "corporate",
    name: "FinCEN MSB Registrant Search",
    url: "https://www.fincen.gov/msb-registrant-search",
    searchType: "business/principal name, registration #, state",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Money-services-business registration data; validate data cadence and public search terms.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "United States — federal",
    category: "warrants",
    name: "U.S. Marshals Service Most Wanted",
    url: "https://www.usmarshals.gov/what-we-do/fugitive-investigations/most-wanted",
    searchType: "name, district, fugitive profile",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Curated high-priority fugitives, not an exhaustive warrant database.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "United States — federal",
    category: "warrants",
    name: "DEA All Fugitives",
    url: "https://www.dea.gov/fugitives/all",
    searchType: "name, offense, regional/profile pagination",
    approach: "ajax_json",
    difficulty: "easy",
    notes:
      "Official paginated list; profile state changes should be treated as live and revalidated.",
    priority: "P1",
    liveStatus: "candidate",
  },
  {
    jurisdiction: "United States — federal",
    category: "warrants",
    name: "ATF Most Wanted",
    url: "https://www.atf.gov/most-wanted",
    searchType: "name, fugitive profile",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Curated wanted list; scrape only if current page terms and robots policy allow it.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "United States — federal",
    category: "warrants",
    name: "DOJ Office of Inspector General Fugitives",
    url: "https://oig.justice.gov/fugitives",
    searchType: "name, offense, reward/profile",
    approach: "ajax_json",
    difficulty: "medium",
    notes: "Curated OIG fugitive profiles, not a general DOJ warrant database.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Texas — Dallas County",
    category: "warrants",
    name: "Dallas County Wanted and Delinquent Offender Lookup",
    url: "https://www.dallascounty.org/dcwantedsearch/search.jsp",
    searchType: "first/last name, ZIP, case/citation, demographics",
    approach: "form_post",
    difficulty: "easy",
    notes:
      "Name search is public; county warns records can lag changes and should not be used for enforcement action.",
    priority: "P1",
    liveStatus: "live",
  },
  {
    jurisdiction: "Arizona — Maricopa County",
    category: "warrants",
    name: "Maricopa County Sheriff Warrant Lookup",
    url: "https://www.mcso.org/i-want-to/warrant-lookup",
    searchType: "first/last name, agency/city/ZIP",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Public table/detail view; preserve agency, warrant date and lookup timestamp.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "United States — federal",
    category: "other",
    name: "NamUs Missing and Unidentified Persons System",
    url: "https://namus.nij.ojp.gov/",
    searchType: "name, case #, demographics, geography",
    approach: "ajax_json",
    difficulty: "hard",
    notes:
      "DOJ-funded public search with case-specific data; not a general criminal record source and no public bulk API is advertised.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "United States — nonprofit / federally partnered",
    category: "other",
    name: "NCMEC MissingKids Search",
    url: "https://www.missingkids.org/gethelpnow/search",
    searchType: "name, age, state, missing date",
    approach: "ajax_json",
    difficulty: "hard",
    notes:
      "Public missing-children listings; use explicit safety, attribution, retention and removal procedures.",
    priority: "P1",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Delaware",
    category: "corporate",
    name: "Delaware Division of Corporations Entity Search",
    url: "https://icis.corp.delaware.gov/Ecorp/EntitySearch/NameSearch.aspx",
    searchType: "entity name, file #, registered agent",
    approach: "form_post",
    difficulty: "medium",
    notes:
      "High-value incorporation jurisdiction; basic public search is not a complete beneficial-owner dataset.",
    priority: "P2",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "California",
    category: "corporate",
    name: "California bizfile Online Business Search",
    url: "https://bizfileonline.sos.ca.gov/search/business",
    searchType: "entity name, entity #, agent/officer where disclosed",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Public registry; filings/images and officer details vary by entity type and time.",
    priority: "P2",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "New York",
    category: "corporate",
    name: "New York Corporation and Business Entity Database",
    url: "https://apps.dos.ny.gov/publicInquiry/",
    searchType: "entity name, DOS ID, assumed name",
    approach: "form_post",
    difficulty: "easy",
    notes:
      "Public entity status/filing data; person linkage can be sparse and should be corroborated.",
    priority: "P2",
    liveStatus: "candidate",
  },
  {
    jurisdiction: "Florida",
    category: "corporate",
    name: "Florida Sunbiz Search Records",
    url: "https://search.sunbiz.org/Inquiry/CorporationSearch/ByName",
    searchType: "entity name, officer/registered-agent name, document #",
    approach: "form_post",
    difficulty: "easy",
    notes:
      "Strong person-to-entity search via officer/agent fields; preserve filing date and document source.",
    priority: "P2",
    liveStatus: "candidate",
  },
  {
    jurisdiction: "Texas",
    category: "corporate",
    name: "Texas Comptroller Taxable Entity Search",
    url: "https://mycpa.cpa.state.tx.us/coa/",
    searchType: "entity name, taxpayer #, state file #",
    approach: "form_post",
    difficulty: "easy",
    notes:
      "Tax-account status, not the complete SOS filing record; SOSDirect has separate account/fee controls.",
    priority: "P2",
    liveStatus: "candidate",
  },
  {
    jurisdiction: "Illinois",
    category: "corporate",
    name: "Illinois Secretary of State Corporate/LLC Search",
    url: "https://apps.ilsos.gov/corporatellc/",
    searchType: "entity name, file #, registered agent",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Public filing search; officer/manager detail depends on entity and filing images.",
    priority: "P2",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Pennsylvania",
    category: "corporate",
    name: "Pennsylvania Business Entity Search",
    url: "https://file.dos.pa.gov/search/business",
    searchType: "entity name, filing #, officer/agent where shown",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Modern business filing portal; inspect network and public-use rules before automation.",
    priority: "P2",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "New Jersey",
    category: "corporate",
    name: "New Jersey Business Records Service",
    url: "https://www.njportal.com/DOR/BusinessNameSearch/Search/BusinessName",
    searchType: "entity name, ID, registered agent",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Entity search is public; documents/certificates can introduce payment/account paths.",
    priority: "P2",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Georgia",
    category: "corporate",
    name: "Georgia Corporations Division Business Search",
    url: "https://ecorp.sos.ga.gov/BusinessSearch",
    searchType: "entity name, control #, officer/agent",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Public entity search; results should be source-linked because names are not unique identifiers.",
    priority: "P2",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Virginia",
    category: "corporate",
    name: "Virginia SCC Clerk's Information System Entity Search",
    url: "https://cis.scc.virginia.gov/EntitySearch/Index",
    searchType: "entity name, SCC ID, registered agent",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Official public registry; filings can expose named officers/agents subject to available disclosure.",
    priority: "P2",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Maryland",
    category: "corporate",
    name: "Maryland Business Express Entity Search",
    url: "https://egov.maryland.gov/BusinessExpress/EntitySearch",
    searchType: "entity name, department ID, resident agent",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Public business lookup; distinguish resident agent from beneficial owner.",
    priority: "P2",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Massachusetts",
    category: "corporate",
    name: "Massachusetts Corporations Division Search",
    url: "https://corp.sec.state.ma.us/CorpWeb/CorpSearch/CorpSearch.aspx",
    searchType: "entity name, ID, officer/agent",
    approach: "form_post",
    difficulty: "easy",
    notes:
      "Legacy public registry; confirm filing-image access and query throttles.",
    priority: "P2",
    liveStatus: "candidate",
  },
  {
    jurisdiction: "Ohio",
    category: "corporate",
    name: "Ohio Business Search",
    url: "https://businesssearch.ohiosos.gov/",
    searchType: "entity name, charter #, agent/officer",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Public filing details; individual names need entity-context validation.",
    priority: "P2",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Michigan",
    category: "corporate",
    name: "Michigan LARA Corporations Search",
    url: "https://cofs.lara.state.mi.us/SearchApi/Search/Search",
    searchType: "entity name, ID, registered agent",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Search endpoint is publicly exposed but undocumented; do not depend on it without permission/version monitoring.",
    priority: "P2",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Minnesota",
    category: "corporate",
    name: "Minnesota Business Filings Online",
    url: "https://mblsportal.sos.state.mn.us/Business/Search?FilingType=Business",
    searchType: "entity name, file #, status",
    approach: "form_post",
    difficulty: "easy",
    notes:
      "Public filings; advanced account actions are separate from basic lookup.",
    priority: "P2",
    liveStatus: "candidate",
  },
  {
    jurisdiction: "Colorado",
    category: "corporate",
    name: "Colorado Business Database Search",
    url: "https://www.sos.state.co.us/biz/BusinessEntityCriteriaExt.do",
    searchType: "entity name, ID, registered agent",
    approach: "form_post",
    difficulty: "easy",
    notes:
      "Public registry; retrieve filing provenance rather than asserting ownership from agent data.",
    priority: "P2",
    liveStatus: "candidate",
  },
  {
    jurisdiction: "Washington",
    category: "corporate",
    name: "Washington Corporations and Charities Filing System",
    url: "https://ccfs.sos.wa.gov/#/BusinessSearch",
    searchType: "entity name, UBI, governor/agent",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "SPA public search; some person roles are disclosed in entity details.",
    priority: "P2",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "North Carolina",
    category: "corporate",
    name: "North Carolina Business Registration Search",
    url: "https://www.sosnc.gov/online_services/search/by_title/_Business_Registration",
    searchType: "entity name, SOS ID, registered agent",
    approach: "form_post",
    difficulty: "easy",
    notes:
      "Public filing data; records may require an entity pivot rather than direct person search.",
    priority: "P2",
    liveStatus: "candidate",
  },
  {
    jurisdiction: "Arizona",
    category: "corporate",
    name: "Arizona Corporation Commission Entity Search",
    url: "https://ecorp.azcc.gov/EntitySearch/Index",
    searchType: "entity name, file #, statutory agent",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Public corporation/LLC data; statutory agent is not necessarily a principal.",
    priority: "P2",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "United Kingdom",
    category: "corporate",
    name: "Companies House Find and Update Company Information",
    url: "https://find-and-update.company-information.service.gov.uk/",
    searchType: "company, officer, PSC, company #",
    approach: "documented_api",
    difficulty: "easy",
    notes:
      "Official REST API requires a key; strong structured company/officer/PSC candidate with explicit docs.",
    priority: "P2",
    liveStatus: "candidate",
  },
  {
    jurisdiction: "New Zealand",
    category: "corporate",
    name: "New Zealand Companies Register",
    url: "https://app.companiesoffice.govt.nz/companies/app/ui/pages/companies/overview",
    searchType: "company, director/shareholder, NZBN/company #",
    approach: "documented_api",
    difficulty: "medium",
    notes:
      "Official registry/data services offer APIs and bulk data; credentials/subscriptions can be required.",
    priority: "P2",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Australia",
    category: "corporate",
    name: "Australian Business Register ABN Lookup",
    url: "https://abr.business.gov.au/",
    searchType: "entity name, ABN, ACN",
    approach: "documented_api",
    difficulty: "medium",
    notes:
      "Official web services require a registered authentication GUID; entity focus, not a people registry.",
    priority: "P2",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "United Kingdom",
    category: "court_cases",
    name: "The National Archives Find Case Law",
    url: "https://caselaw.nationalarchives.gov.uk/",
    searchType: "party/case name, neutral citation, text, court/date",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Official judgments/case-law corpus, not a complete live docket; validate any search endpoint terms.",
    priority: "P2",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Council of Europe",
    category: "court_cases",
    name: "European Court of Human Rights HUDOC",
    url: "https://hudoc.echr.coe.int/",
    searchType: "case title/applicant, application #, text, respondent state",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Official case-law corpus with advanced filters; current public search is broad but not a person-verification source.",
    priority: "P2",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "European Union",
    category: "court_cases",
    name: "Court of Justice of the European Union InfoCuria",
    url: "https://curia.europa.eu/juris/recherche.jsf?language=en",
    searchType: "case #, party, subject, date",
    approach: "form_post",
    difficulty: "easy",
    notes:
      "Official EU Court and General Court decisions/proceedings; party names are context-specific.",
    priority: "P2",
    liveStatus: "candidate",
  },
  {
    jurisdiction: "Canada — federal",
    category: "court_cases",
    name: "Supreme Court of Canada Decisions Database",
    url: "https://scc-csc.lexum.com/scc-csc/en/nav.do",
    searchType: "case name/party, citation, docket #, text",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Official Supreme Court corpus hosted by Lexum; not provincial/federal trial court coverage.",
    priority: "P2",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Texas — Harris County",
    category: "property",
    name: "Harris Central Appraisal District Quick Search",
    url: "https://hcad.org/quicksearch/",
    searchType: "owner name, address, account #",
    approach: "public_api",
    difficulty: "easy",
    notes:
      "Official ArcGIS parcel service may expose owner fields; validate schema, exemptions and service terms before automation.",
    priority: "P3",
    liveStatus: "candidate",
  },
  {
    jurisdiction: "California — Los Angeles County",
    category: "property",
    name: "Los Angeles County Assessor Property Portal",
    url: "https://portal.assessor.lacounty.gov/",
    searchType: "APN/address; owner details where disclosed",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Primarily parcel/address pivot rather than broad person-name search; use only as a corroborating linkage source.",
    priority: "P3",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "New York City",
    category: "property",
    name: "ACRIS Recorded Property Documents",
    url: "https://a836-acris.nyc.gov/CP/",
    searchType: "party/grantor/grantee name, address, BBL, document #",
    approach: "form_post",
    difficulty: "medium",
    notes:
      "Official records for Manhattan, Bronx, Brooklyn and Queens from 1966; Staten Island uses a separate system.",
    priority: "P3",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "New York City",
    category: "property",
    name: "NYC Property Search",
    url: "https://property.cityofnewyork.us/",
    searchType: "address, BBL, account; owner detail where disclosed",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Address/parcel-led, not a complete owner-name index; combine only with provenance and date.",
    priority: "P3",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Florida — Miami-Dade County",
    category: "property",
    name: "Miami-Dade Property Appraiser Search",
    url: "https://www.miamidade.gov/Apps/PA/PropertySearch/#/",
    searchType: "owner name, address, folio",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "High-value owner/property pivot; statutory redactions and update timing must be honored.",
    priority: "P3",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Arizona — Maricopa County",
    category: "property",
    name: "Maricopa County Assessor Parcel Search",
    url: "https://mcassessor.maricopa.gov/",
    searchType: "owner name, address, parcel/APN",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Public assessor data; name matching has high collision risk without parcel/address evidence.",
    priority: "P3",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Washington — King County",
    category: "property",
    name: "King County eReal Property Search",
    url: "https://blue.kingcounty.com/Assessor/eRealProperty/default.aspx",
    searchType: "owner name, address, parcel",
    approach: "form_post",
    difficulty: "easy",
    notes:
      "Official assessor lookup; property ownership should be tied to current record date.",
    priority: "P3",
    liveStatus: "candidate",
  },
  {
    jurisdiction: "Illinois — Cook County",
    category: "property",
    name: "Cook County Assessor Property Search",
    url: "https://www.cookcountyassessor.com/address-search",
    searchType: "address/PIN; owner in parcel details where disclosed",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Address/PIN-first search, not reliable as a general name lookup; verify owner field availability.",
    priority: "P3",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Nevada — Clark County",
    category: "property",
    name: "Clark County Recorder Public Records Search",
    url: "https://recorder.co.clark.nv.us/RecorderEcommerce/",
    searchType: "grantor/grantee name, document #, date",
    approach: "form_post",
    difficulty: "medium",
    notes:
      "Recorded-document party search rather than tax-roll ownership; documents/fees may have separate rules.",
    priority: "P3",
    liveStatus: "portal_only",
  },
  {
    jurisdiction: "Pennsylvania — Philadelphia",
    category: "property",
    name: "Philadelphia Property Search",
    url: "https://property.phila.gov/",
    searchType: "owner name, address, account/OPA #",
    approach: "ajax_json",
    difficulty: "medium",
    notes:
      "Official property data; treat owner names as dated assessor records and retain source/retrieval time.",
    priority: "P3",
    liveStatus: "portal_only",
  },
];

export function filterPortalBacklog(options?: {
  priority?: Array<"P0" | "P1" | "P2" | "P3">;
  category?: PortalBacklogCategory;
  stateHint?: string;
  liveOnly?: boolean;
  limit?: number;
}): PortalBacklogEntry[] {
  const priorities = options?.priority ?? ["P0", "P1", "P2", "P3"];
  const limit = options?.limit ?? 200;
  const hint = options?.stateHint?.toLowerCase();

  return PORTAL_BACKLOG.filter((row) => priorities.includes(row.priority))
    .filter((row) => !options?.category || row.category === options.category)
    .filter((row) => !options?.liveOnly || row.liveStatus === "live")
    .filter((row) => !hint || row.jurisdiction.toLowerCase().includes(hint))
    .slice(0, limit);
}
